# 1.

The list_ variable is a Python list, while array_list is a NumPy array.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# 2.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# 3.

With the specified dtype=int argument, the elements in array_list will be of integer type, whereas the elements in list_ will remain as strings.

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# 4.

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape_of_num_array = num_array.shape

# (ii) Find the size of num_array
size_of_num_array = num_array.size

# Print the results
print("Shape of num_array:", shape_of_num_array)
print("Size of num_array:", size_of_num_array)


Shape of num_array: (2, 3)
Size of num_array: 6


# 5.

In [6]:
import numpy as np

# Create a 3x3 matrix of zeros
zeros_array = np.zeros((3, 3))

# Print the result
print("Numpy array of 3x3 matrix containing zeros:")
print(zeros_array)


Numpy array of 3x3 matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 6.

In [7]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the result
print("Identity matrix of shape (5, 5):")
print(identity_matrix)


Identity matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
